import React, {useContext} from "react";
import type {NextPage} from 'next';
import Head from 'next/head';
import {Header} from "../components/header";
import {ProductContext} from "../components/productContext";
import Link from "next/link";

const TestButton = () => {
	const ctx = useContext(ProductContext);

	return (
		<>
			<button onClick={() => console.log(ctx.GetState())}>
				Log context
			</button>
			<button onClick={() => {
				ctx.AddToCart({
					type: "IProduct",
					id: ctx.GetId(),
					name: "Test product - " + ctx.GetId(),
					onSale: false,
					price: 0,
					quantity: 0,
					series: ""
				});
			}}>
				Add to cart
			</button>
			<button onClick={() => {
				const state = ctx.GetState();
				ctx.RemoveFromCart(state.cart[state.cart.length - 1]);
			}}>Remove from cart
			</button>
		</>
	)
}

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Wallpapa</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<Header/>
			<main>
				<Link href={"./testpage"}>Test Page</Link>
				<TestButton/>
				<br/>
				<ProductContext.Consumer>
					{ctx => ctx.GetState().cart.map(product =>
						<div key={product.id}>
							{product.name}
							<button onClick={() => ctx.RemoveFromCart(product)}>X</button>
						</div>
					)}
				</ProductContext.Consumer>
			</main>

			<footer>Footer</footer>
		</div>
	)
}

export default Home
